### ISSUE TITLE
emsc error,javascript error 

### ISSUE THREAD

**Issue by dguimard** [floooh/sokol-samples#56] opened 2020-04-29 13:55 UTC
Hello Sir ,

i have the following error doing the next step :
./fips setup emscripten

> ./fips set config webgl2-emsc-make-release
> ./fips build
> ./fips list targets
> ./fips run triangle-emsc
 failed with the next error : 
'Document': The provided selector is empty.,Error: Failed to execute 'querySelector' on 'Document': The provided selector is empty.
    at __findEventTarget (http://localhost:8080/triangle-emsc.js:1:15800)
    at __registerUiEventCallback (http://localhost:8080/triangle-emsc.js:1:37924)
    at _emscripten_set_resize_callback_on_thread (http://localhost:8080/triangle-emsc.js:1:38755)
    at wasm-function[70]:0x3ea9
    at wasm-function[75]:0x6ff7
    at Module._main (http://localhost:8080/triangle-emsc.js:1:59226)
    at callMain (http://localhost:8080/triangle-emsc.js:1:60012)
    at doRun (http://localhost:8080/triangle-emsc.js:1:60590)
    at http://localhost:8080/triangle-emsc.js:1:60745

**Comment by floooh** [comment] 2020-04-29 14:32
Thanks for the bug report. 

This was indeed an oversight, caused by a somewhat recent change in the emscripten SDK and I forgot to update the "raw" emscripten samples (I only fixed sokol_app.h).

The bug has already been fixed in the webgpu branch which I'll merge back to master in the next few days (this is the commit: https://github.com/floooh/sokol-samples/commit/5c744ac2eb90944b0f59c4931712cc754a9d1a2f).

**Closed by floooh** 2020-04-29 14:32 UTC
