### ISSUE TITLE
Cannot build sapp samples on macOS Catalina 

### ISSUE THREAD

**Issue by nightlifelover** [floooh/sokol-samples#62] opened 2020-07-22 10:01 UTC
When running `./fips build` I get the following error:

```
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target x86_64-apple-macos10.15 -fmessage-length=158 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -DFIPS_APP_WINDOWED=1 -DSOKOL_NO_DEPRECATED -DSOKOL_GLCORE33 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -I/Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug/include -I/Users/nils/Develop/fips-cimgui -I/Users/nils/Develop/fips-glfw/glfw/include -I/Users/nils/Develop/fips-imgui/imgui -I/Users/nils/Develop/fips-libmodplug/libmodplug/src -I/Users/nils/Develop/sokol -I/Users/nils/Develop/sokol/util -I/Users/nils/Develop/sokol-samples/libs -I/Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp -I/Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/DerivedSources-normal/x86_64 -I/Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/DerivedSources/x86_64 -I/Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug -fstrict-aliasing -Wno-multichar -Wall -Wextra -Wno-expansion-to-defined -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wno-long-long -Wno-overloaded-virtual -Wno-unused-volatile-lvalue -Wno-deprecated-writable-strings -fno-stack-check -Wno-missing-field-initializers -D_DEBUG_ -D_DEBUG -DFIPS_DEBUG=1 -Wno-return-type-c-linkage -std=gnu99 -g -MMD -MT dependencies -MF /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/Objects-normal/x86_64/pixelformats-sapp.d --serialize-diagnostics /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/Objects-normal/x86_64/pixelformats-sapp.dia -c /Users/nils/Develop/sokol-samples/sapp/pixelformats-sapp.c -o /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/Objects-normal/x86_64/pixelformats-sapp.o
/Users/nils/Develop/sokol-samples/sapp/pixelformats-sapp.c:337:9: warning: implicit declaration of function 'igBeginChildStr' is invalid in C99
      [-Wimplicit-function-declaration]
        igBeginChildStr("#scrollregion", (ImVec2){0,0}, false, ImGuiWindowFlags_None);
        ^
1 warning generated.

Ld /Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug/pixelformats-sapp.app/Contents/MacOS/pixelformats-sapp normal x86_64 (in target 'pixelformats-sapp' from project 'sokol-samples')
    cd /Users/nils/Develop/sokol-samples
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug -F/Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug -filelist /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/Objects-normal/x86_64/pixelformats-sapp.LinkFileList -Xlinker -no_deduplicate -stdlib=libc++ -ObjC -dead_strip -lpthread -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/libs/sokol/Debug/libsokol.a /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/fips-cimgui_cimgui/Debug/libcimgui.a -framework Foundation -framework IOKit -framework Cocoa -framework QuartzCore -framework OpenGL -framework AudioToolbox -Xlinker -dependency_info -Xlinker /Users/nils/Develop/fips-build/sokol-samples/sapp-osx-xcode-debug/sapp/sokol-samples.build/Debug/pixelformats-sapp.build/Objects-normal/x86_64/pixelformats-sapp_dependency_info.dat -o /Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug/pixelformats-sapp.app/Contents/MacOS/pixelformats-sapp
Undefined symbols for architecture x86_64:
  "_igBeginChildStr", referenced from:
      _frame in pixelformats-sapp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
    Ld /Users/nils/Develop/fips-deploy/sokol-samples/sapp-osx-xcode-debug/pixelformats-sapp.app/Contents/MacOS/pixelformats-sapp normal x86_64
(1 failure)
[ERROR] Failed to build config 'sapp-osx-xcode-debug' of project 'sokol-samples'
```

Since it complained about the implicit declaration of `igBeginChildStr` I tried including `sokol_gfx_imgui.h`. But this only fixed the warning and not the linker error. Why is the linker looking for `_igBeginChildStr` and not just `igBeginChildStr`?

My Xcode version:

```
sokol-samples 🍎 xcodebuild -version
Xcode 11.5
Build version 11E608c```

**Comment by floooh** [comment] 2020-07-22 10:15
Hi, these are fairly new functions in the cimgui library (the "Str" postfix is new), so it looks like something isn't uptodate. Please try the following in the sokol-samples directory:

```
> git pull
> ./fips update
> ./fips clean
> ./fips build
```

(the ```./fips update``` is the important part)

If this doesn't work, please try a completely new checkout, e.g.:

```
> cd ~
> mkdir scratch
> cd scratch
> git clone https://github.com/floooh/sokol-samples
> cd sokol-samples
> ./fips set config sapp-metal-osx-xcode-debug
> ./fips build
```

(I just tested it here and it worked)

The '_' is normal, this is the 'internal' name for C functions as seen by the linker.

**Comment by nightlifelover** [comment] 2020-07-22 14:17
I got it working again, but only by cloning it into a  newly created directory, after fips update I ran into a problem with the build system in the original directory.

Thanks!

**Comment by floooh** [comment] 2020-07-22 16:55
Hmm interestingly I'm currently seeing a somewhat similar strange problem on Windows. I'm seeing this error when compiling pixelformats-sapp:

```
E:\projects\sokol\util\sokol_imgui.h(249): fatal error C1189: #error:  "Please include imgui.h before the sokol_imgui.h implementation" [E:\projects\fips-build\sokol-samples\sapp-d3d11-win64-vscode-debug\sapp\pixelformats-sapp.vcx
proj]
```

I'm investigating...

**Comment by floooh** [comment] 2020-07-22 17:00
Hmm ok, this is a strange one, the Visual Studio compiler thinks it's it C++ mode (__cplusplus is defined) in a .c file... investigating intensified...

**Comment by floooh** [comment] 2020-07-22 17:10
Ok, this particular problem seems to be caused by cmake 3.18.

Seems like cmake 3.18 wants to compiler .c files as C++ at least in Visual Studio... now I need to check if cmake has the same broken behaviour on macOS...

**Comment by nightlifelover** [comment] 2020-07-22 17:50
I have an older version:

```
🍎 cmake --version
cmake version 3.10.1
```

**Comment by floooh** [comment] 2020-07-22 19:37
Yeah, the issue also seems to be in the cmake 3.18 Visual Studio generator only, looks like cmake is leaving the C vs C++ detection up to Visual Studio now, and for some reason Visual Studio wants to compile some .c files as C++. I have added a workaround to fips to force .c files to be compiled in C mode now if the Visual Studio cmake generator is used.

Anyway, I'm closing the issue now :)

**Closed by floooh** 2020-07-22 19:37 UTC
